---
- Scenario: "SameVersion"
  description: "A mapping between oad rules and breaking change rules"
  rules:
    - id: "1039"
      name: "AddedOperation"
      severity:
        original: "info|warning" 
        new: "error"
      comments: "It's not allowed per new breaking change policy"
      
    - id: "1038"
      name: "AddedPath"
      severity:
        original: "info|warning" 
        new: "error"
      comments: "It's not allowed per new breaking change policy"
      
- Scenario: "CrossVersion"
  description: "A mapping between oad rules and breaking change rules"
  rules:
    - id: "1020"
      name: "AddedEnumValue"
      severity:
        original: "info|error|warning" 
        new: "warning"
      comments: "It's allowed in new version."
      
    - id: "1025"
      name: "RequiredStatusChange"
      severity:
        original: "info|error|warning" 
        new: "warning"
      comments: "It's allowed in new version."  
      
    - id: "1041"
      name: "AddedPropertyInResponse"
      severity:
        original: "info|error|warning" 
        new: "warning"
      comments: "It's allowed in new version."
      
    - id: "1029"
      name: "ReadonlyPropertyChanged"
      severity:
        original: "info|error|warning" 
        new: "warning"
      comments: "It's allowed in new version."
      
    - id: "1021"
      name: "AddedAdditionalProperties"
      severity:
        original: "info|error|warning" 
        new: "warning"
      comments: "It's allowed in new version."
      
    - id: "1011"
      name: "AddingResponseCode"
      severity:
        original: "info|error|warning" 
        new: "warning"
      comments: "It's allowed in new version."
