pool:
  vmImage: "ubuntu-18.04"

name: Merge Validation
trigger:
  - master
pr:
  - master

jobs:
  - job: SecurityTools
    pool:
      vmImage: "windows-latest"
    steps:
      - task: PoliCheck@1
        inputs:
          inputType: "Basic"
          targetType: "F"
          targetArgument: "$(Build.SourcesDirectory)"
          result: "PoliCheck.xml"
      - task: PostAnalysis@1
        inputs:
          AllTools: false
          APIScan: false
          BinSkim: false
          CodesignValidation: false
          CredScan: false
          FortifySCA: false
          FxCop: false
          ModernCop: false
          PoliCheck: true
          PoliCheckBreakOn: "Severity2Above"
          RoslynAnalyzers: false
          SDLNativeRules: false
          Semmle: false
          TSLint: false
          ToolLogsNotFoundAction: "Standard"
